apiVersion: 1

datasources:
  - name: ClickHouse
    uid: clickhouse-igra
    type: grafana-clickhouse-datasource
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      host: clickhouse
      port: 8123
      protocol: http
      secure: false
      username: default
      defaultDatabase: tidx_38833
      dialTimeout: 10
      queryTimeout: 60

  - name: Prometheus
    uid: prometheus-igra
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: true
