use std::path::PathBuf;

use anyhow::{bail, Result};
use clap::Args as ClapArgs;
use dialoguer::Input;

#[derive(ClapArgs)]
pub struct Args {
    /// Output path for config file
    #[arg(short, long, default_value = "config.toml")]
    pub output: PathBuf,

    /// Overwrite existing config file
    #[arg(long)]
    pub force: bool,
}

pub fn run(args: Args) -> Result<()> {
    if args.output.exists() && !args.force {
        bail!(
            "Config file already exists: {}. Use --force to overwrite.",
            args.output.display()
        );
    }

    println!("\n🔫 tidx init\n");

    let name: String = Input::new()
        .with_prompt("Chain name")
        .interact_text()?;

    let chain_id: u64 = Input::new()
        .with_prompt("Chain ID")
        .interact_text()?;

    let rpc_url: String = Input::new()
        .with_prompt("RPC URL")
        .interact_text()?;

    let pg_url: String = Input::new()
        .with_prompt("PostgreSQL URL")
        .default("postgres://localhost:5432/tidx".to_string())
        .interact_text()?;

    let http_port: u16 = Input::new()
        .with_prompt("HTTP API port")
        .default(8080)
        .interact_text()?;

    let config = generate_config(&name, chain_id, &rpc_url, &pg_url, http_port);

    std::fs::write(&args.output, &config)?;

    println!("\n✅ Config written to {}", args.output.display());
    println!("\nNext steps:");
    println!("  1. Start PostgreSQL");
    println!("  2. Run: tidx up");
    println!("  3. Query: curl \"http://localhost:{http_port}/query?chainId={chain_id}&sql=SELECT * FROM blocks LIMIT 5\"");

    Ok(())
}

fn generate_config(
    name: &str,
    chain_id: u64,
    rpc_url: &str,
    pg_url: &str,
    http_port: u16,
) -> String {
    format!(
        r#"# tidx configuration
# Generated by `tidx init`

[http]
enabled = true
port = {http_port}
bind = "0.0.0.0"

[prometheus]
enabled = true
port = 9090

[[chains]]
name = "{name}"
chain_id = {chain_id}
rpc_url = "{rpc_url}"
pg_url = "{pg_url}"
backfill = true
batch_size = 100
"#
    )
}
